import { useState }         from "react";
import { X, FileText, MessageSquare, Download, User, DollarSign, TrendingUp, Zap } from "lucide-react";
import institutionSupabase  from "@/institution/lib/institutionSupabase";
import RequestChat          from "@/shared/components/RequestChat";

import type { MarketplaceRequest } from "@/institution/types/institution";
import { SectionLabel, DetailStat, ProfileStat } from "./MarketplacePrimitives";

interface RequestDetailDrawerProps {
  request:  MarketplaceRequest;
  onClose:  () => void;
  onBid:    () => void;
}

const fmt      = (v: number) => v >= 1_000_000 ? `MUR ${(v / 1_000_000).toFixed(1)}M` : `MUR ${Number(v).toLocaleString()}`;
const fmtDate  = (s: string) => new Date(s).toLocaleDateString("en-MU", { day: "numeric", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" });
const fmtMoney = (v: number | null | undefined) => v != null && v > 0 ? fmt(v) : "—";

export function RequestDetailDrawer({ request, onClose, onBid }: RequestDetailDrawerProps) {
  const [tab,             setTab]             = useState<"details" | "chat">("details");
  const [markerComment,   setMarkerComment]   = useState("");
  const [approverComment, setApproverComment] = useState("");

  const isUrgent = new Date(request.bid_window_closes_at).getTime() - Date.now() < 60 * 60 * 1000;

  const downloadPDF = () => {
    const lines = [
      `FICIUM — REQUEST DOSSIER`,
      `Generated: ${new Date().toLocaleString("en-MU")}`,
      `${"─".repeat(48)}`,
      `Product:        ${request.product_label ?? request.product_type}`,
      `Family:         ${request.family_label ?? "—"}`,
      `Status:         Open`,
      `Amount:         ${fmt(Number(request.amount))}`,
      `Term:           ${request.term_months ? `${request.term_months} months` : "—"}`,
      `Submitted:      ${fmtDate(request.created_at)}`,
      `Bid window:     ${fmtDate(request.bid_window_closes_at)}`,
      `Ref:            #${request.client_ref?.slice(0, 8)}`,
      ...(request.purpose ? [`Purpose:        ${request.purpose}`] : []),
      `${"─".repeat(48)}`,
      `ANONYMOUS CLIENT PROFILE`,
      `Debt-to-Income: ${request.client_debt_to_income_ratio != null ? `${(request.client_debt_to_income_ratio * 100).toFixed(0)}%` : "—"}`,
      `Affordability:  ${request.client_affordability_score != null ? `${request.client_affordability_score}/100` : "—"}`,
      `Risk Score:     ${request.client_risk_score != null ? `${request.client_risk_score}/100` : "—"}`,
      `Monthly Income: ${fmtMoney(request.client_monthly_income)}`,
      `Net Worth:      ${fmtMoney(request.client_net_worth)}`,
      `Country:        ${request.client_country ?? "—"}`,
      ...(markerComment   ? [`\nMarker note:    ${markerComment}`]   : []),
      ...(approverComment ? [`Approver note:  ${approverComment}`] : []),
      `${"─".repeat(48)}`,
      `CONFIDENTIAL — For internal use only. Client identity not disclosed.`,
    ];
    const html = `<!DOCTYPE html><html><head><meta charset="utf-8">
      <title>Ficium Request Dossier #${request.client_ref?.slice(0, 8)}</title>
      <style>body{font-family:'Courier New',monospace;font-size:13px;padding:40px;max-width:680px;margin:0 auto;color:#1a1a2e}.logo{font-size:22px;font-weight:900;letter-spacing:-0.5px;color:#2563eb;margin-bottom:4px}.subtitle{font-size:11px;color:#888;text-transform:uppercase;letter-spacing:2px;margin-bottom:32px}pre{white-space:pre-wrap;word-break:break-word;background:#f8f7f4;padding:24px;border-radius:8px;border:1px solid #e5e5e0}.footer{margin-top:24px;font-size:11px;color:#aaa;border-top:1px solid #e5e5e0;padding-top:12px}@media print{body{padding:20px}}</style>
    </head><body>
      <div class="logo">Ficium</div>
      <div class="subtitle">Request Dossier — Confidential</div>
      <pre>${lines.join("\n")}</pre>
      <div class="footer">This document is for internal use only. Generated by Ficium Institution Portal.</div>
      <script>window.onload=()=>window.print();</script>
    </body></html>`;
    const blob = new Blob([html], { type: "text/html" });
    const url  = URL.createObjectURL(blob);
    window.open(url, "_blank");
    setTimeout(() => URL.revokeObjectURL(url), 10000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-8 bg-ink/50 backdrop-blur-sm" onClick={onClose}>
      <div className="relative bg-white rounded-3xl shadow-[0_32px_80px_rgba(10,10,26,0.28)] w-full max-w-3xl max-h-[92vh] flex flex-col overflow-hidden"
           onClick={(e) => e.stopPropagation()}>

        {/* Header */}
        <div className="flex items-start justify-between px-8 py-6 border-b border-ink/[0.07] flex-shrink-0">
          <div>
            <div className="text-[11px] font-bold text-ficium uppercase tracking-widest mb-1">{request.family_label ?? "Financial product"}</div>
            <h2 className="font-display font-bold text-[24px] text-ink leading-tight">{request.product_label ?? request.product_type}</h2>
          </div>
          <div className="flex items-center gap-2 mt-1">
            <button onClick={downloadPDF} title="Download dossier"
              className="flex items-center gap-1.5 text-[12px] font-semibold text-muted hover:text-ficium border border-ink/10 hover:border-ficium/30 px-3.5 py-2 rounded-xl transition-colors">
              <Download className="w-3.5 h-3.5" /> PDF
            </button>
            <button onClick={onClose} className="w-9 h-9 rounded-xl bg-ink/[0.05] hover:bg-ink/10 grid place-items-center text-muted hover:text-ink transition-colors">
              <X className="w-4.5 h-4.5" />
            </button>
          </div>
        </div>

        {/* Tabs */}
        <div className="flex border-b border-ink/[0.07] flex-shrink-0 px-8">
          {(["details", "chat"] as const).map((t) => (
            <button key={t} onClick={() => setTab(t)}
              className={`flex items-center gap-2 py-3.5 mr-6 text-[13px] font-semibold transition-colors border-b-2 ${
                tab === t ? "border-ficium text-ficium" : "border-transparent text-muted hover:text-ink"
              }`}>
              {t === "details" ? <FileText className="w-3.5 h-3.5" /> : <MessageSquare className="w-3.5 h-3.5" />}
              {t.charAt(0).toUpperCase() + t.slice(1)}
            </button>
          ))}
        </div>

        {/* Body */}
        {tab === "details" ? (
          <div className="flex-1 overflow-y-auto">
            <div className="px-8 py-6 space-y-7">
              <div className="grid grid-cols-3 gap-3">
                <DetailStat label="Status"><span className="bg-green-50 text-green-700 border border-green-200 text-[11px] font-semibold px-2.5 py-1 rounded-full">Open</span></DetailStat>
                <DetailStat label="Submitted" value={fmtDate(request.created_at)} />
                <DetailStat label="Ref" value={`#${request.client_ref?.slice(0, 8)}`} />
                <DetailStat label="Amount" value={fmt(Number(request.amount))} bold />
                {request.term_months && <DetailStat label="Term" value={`${request.term_months} months`} bold />}
                {request.bid_window_closes_at && (
                  <DetailStat label="Bid window closes" value={fmtDate(request.bid_window_closes_at)} accent={isUrgent ? "red" : undefined} />
                )}
              </div>

              {request.purpose && (
                <div>
                  <SectionLabel icon={<FileText className="w-3.5 h-3.5" />} text="Purpose" />
                  <p className="text-[14px] text-ink/80 bg-cream rounded-xl px-4 py-3 leading-relaxed">{request.purpose}</p>
                </div>
              )}

              <div className="grid grid-cols-2 gap-6">
                <div>
                  <div className="flex items-center justify-between mb-3">
                    <SectionLabel icon={<User className="w-3.5 h-3.5" />} text="Client Profile" />
                    <span className="text-[10px] text-muted bg-ink/5 px-2 py-1 rounded-full">Anonymised</span>
                  </div>
                  <div className="grid grid-cols-2 gap-2">
                    <ProfileStat label="Debt-to-Income" value={request.client_debt_to_income_ratio != null ? `${(request.client_debt_to_income_ratio * 100).toFixed(0)}%` : "—"} accent={request.client_debt_to_income_ratio != null ? (request.client_debt_to_income_ratio <= 0.35 ? "green" : request.client_debt_to_income_ratio <= 0.50 ? "amber" : "red") : undefined} />
                    <ProfileStat label="Affordability"  value={request.client_affordability_score != null ? `${request.client_affordability_score}/100` : "—"} accent={request.client_affordability_score != null ? (request.client_affordability_score >= 70 ? "green" : request.client_affordability_score >= 50 ? "amber" : "red") : undefined} />
                    <ProfileStat label="Risk Score"     value={request.client_risk_score != null ? `${request.client_risk_score}/100` : "—"} />
                    <ProfileStat label="Monthly Income" value={fmtMoney(request.client_monthly_income)} />
                    <ProfileStat label="Net Worth"      value={fmtMoney(request.client_net_worth)} />
                    <ProfileStat label="Country"        value={request.client_country ?? "—"} />
                  </div>
                  <p className="text-[10px] text-muted mt-2">Client identity not disclosed at this stage.</p>
                </div>

                <div className="space-y-4">
                  <div>
                    <SectionLabel icon={<DollarSign className="w-3.5 h-3.5" />} text="Requested Amount" />
                    <div className="bg-cream rounded-xl px-4 py-3">
                      <div className="font-display font-bold text-[24px] text-ink">{fmt(Number(request.amount))}</div>
                      {request.term_months && <div className="text-[13px] text-muted mt-0.5">over {request.term_months} months</div>}
                    </div>
                  </div>
                  <div>
                    <SectionLabel icon={<TrendingUp className="w-3.5 h-3.5" />} text="Rate Guidance" />
                    <div className="bg-cream rounded-xl px-4 py-3 text-[13px] text-ink/70 leading-relaxed">
                      Submit your most competitive rate. Clients compare all bids and are not shown your institution name until they choose to connect.
                    </div>
                  </div>
                </div>
              </div>

              {/* Maker-checker comments */}
              <div className="grid grid-cols-2 gap-4 pt-2">
                {[
                  { label: "Marker Comment",   color: "ficium", value: markerComment,   set: setMarkerComment,   placeholder: "Add your analysis or notes before submitting for approval…" },
                  { label: "Approver Comment", color: "amber",  value: approverComment, set: setApproverComment, placeholder: "Approver review notes — reasons for approval or rejection…" },
                ].map(({ label, color, value, set, placeholder }) => (
                  <div key={label}>
                    <div className="flex items-center gap-2 mb-2">
                      <div className={`w-5 h-5 rounded-md bg-${color === "ficium" ? "ficium/10" : "amber-100"} grid place-items-center`}>
                        <MessageSquare className={`w-3 h-3 text-${color === "ficium" ? "ficium" : "amber-600"}`} />
                      </div>
                      <span className={`text-[11px] font-bold text-${color === "ficium" ? "ficium" : "amber-600"} uppercase tracking-wider`}>{label}</span>
                    </div>
                    <textarea value={value} onChange={(e) => set(e.target.value)} rows={4} placeholder={placeholder}
                      className={`w-full bg-white border border-ink/[0.10] focus:border-${color === "ficium" ? "ficium" : "amber-400"} focus:ring-2 focus:ring-${color === "ficium" ? "ficium" : "amber-400"}/15 rounded-2xl px-4 py-3 text-[13px] text-ink placeholder:text-muted/60 outline-none resize-none transition-all`} />
                  </div>
                ))}
              </div>
            </div>
          </div>
        ) : (
          <div className="flex-1 flex flex-col overflow-hidden">
            <RequestChat requestId={request.id} senderType="institution" client={institutionSupabase} />
          </div>
        )}

        {/* Footer CTA */}
        {tab === "details" && (
          <div className="flex-shrink-0 bg-white border-t border-ink/[0.07] px-8 py-5 flex items-center gap-4">
            <button onClick={onBid}
              className="flex-1 flex items-center justify-center gap-2 bg-ficium hover:bg-ficium-deep text-white font-bold py-3.5 rounded-2xl transition-colors text-[15px] shadow-ficium">
              <Zap className="w-5 h-5" /> Place bid on this request
            </button>
            <button onClick={onClose} className="px-6 py-3.5 rounded-2xl border border-ink/10 text-muted text-[14px] font-semibold hover:bg-ink/[0.03] transition-colors">
              Close
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
